services:
  backend:
    build:
      context: ./backend
    container_name: elixir_backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    tty: true
    stdin_open: true

  postgres:
    image: postgres:16
    container_name: elixir_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elixir_app_mensagem_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d elixir_app_mensagem_dev"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
